config/routes.rb
Rails.application.routes.draw do
  get 'reviews/create'
  get 'reviews/destroy'
  get 'bookmarks/new'
  get 'bookmarks/destroy'
  get 'lists/index'
  get 'lists/show'
  get 'lists/new'
  get 'lists/create'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  root 'lists#index'
  resources :lists, except: [:update, :edit] do
    resources :bookmarks, only: [:new, :create]
    resources :reviews, only: :create
  end
  resources :bookmarks, only: :destroy
  resources :reviews, only: :destroy
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/bookmark.rb
class Bookmark < ApplicationRecord
  belongs_to :movie
  belongs_to :list

  validates :comment, length: { minimum: 6 }
  validates :movie, uniqueness: { scope: :list, message: 'already added' }
end

app/models/list.rb
class List < ApplicationRecord
  has_many :bookmarks, dependent: :destroy
  has_many :movies, through: :bookmarks
  has_many :reviews, dependent: :destroy

  validates :name, presence: true, uniqueness: true
end

app/models/movie.rb
class Movie < ApplicationRecord
  has_many :bookmarks

  validates :title, :overview, presence: true, uniqueness: true
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :list

  validates :rating, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/bookmarks_controller.rb
class BookmarksController < ApplicationController
  before_action :select_list, only: [:new, :create]
  def new
    @bookmark = Bookmark.new
  end

  def create
    @bookmark = Bookmark.new(bookmark_params)
    @bookmark.list = @list
    if @bookmark.save
      redirect_to list_path(@list)
    else
      render :new, status: :unprocessable_entity
    end
  end

  def destroy
    @bookmark = Bookmark.find(params[:id])
    @bookmark.destroy
    redirect_to list_path(@bookmark.list), status: :see_other
  end

  private

  def select_list
    @list = List.find(params[:list_id])
  end

  def bookmark_params
    params.require(:bookmark).permit(:comment, :movie_id)
  end
end

# def create
#   @movie = Movie.where(params[:bookmark][:movie])
#   @comment = params[:bookmark][:comment]
#   @bookmark = Bookmark.new(list: @list, movie: @movie, comment: @comment)
#   if @bookmark.save
#     redirect_to list_path(@list)
#   else
#     render :new, status: :unprocessable_entity
#   end
# end

app/controllers/lists_controller.rb
class ListsController < ApplicationController
  before_action :select_list, only: [:show, :destroy]

  def index
    @lists = List.all
  end

  def show
    @bookmark = Bookmark.new
    @review = Review.new(list: @list)
  end

  def new
    @list = List.new
  end

  def create
    @list = List.new(list_params)
    if @list.save
      redirect_to list_path(@list)
    else
      render :new, status: :unprocessable_entity
    end
  end

  def destroy
    @list.destroy
    redirect_to lists_path, status: :see_other
  end

  private

  def select_list
    @list = List.find(params[:id])
  end

  def list_params
    params.require(:list).permit(:name)
  end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  def create
    @review = Review.new(review_params)
    @list = List.find(params[:list_id])
    @review.list = @list
    if @review.save
      redirect_to list_path(@list)
    else
      render list_path(@list), status: :unprocessable_entity
    end
  end

  def destroy
    @review = Review.find(params[:id])
    @review.destroy
    redirect_to list_path(@review.list)
  end

  private

  def review_params
    params.require(:review).permit(:comment, :rating)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bookmarks_helper.rb
module BookmarksHelper
end

app/helpers/lists_helper.rb
module ListsHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/views/bookmarks/destroy.html.erb
<h1>Bookmarks#destroy</h1>
<p>Find me in app/views/bookmarks/destroy.html.erb</p>

app/views/bookmarks/new.html.erb
<div class="card-category" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)), url(https://images.unsplash.com/photo-1543536448-1e76fc2795bf?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=1678&q=80)">
</div>

<div class="container my-4">
  <div class="row">
    <h1>Add a movie on our "<%= @list.name %>" list</h1>
    <p>Fulfill the information from the form:</p>
      <%= simple_form_for [@list, @bookmark] do |f| %>
        <%= f.association :movie, collection: Movie.all.order(:title), input_html: {data: { controller: "tom-select"}} %>
        <%= f.input :comment %>
          <%# <%= f.association :tag %>
          <%= f.submit "Add movie", class: 'btn btn-flat' %>
      <% end %>
      <div class ="mt-4" id="back">
        <%= link_to "Back to our list", list_path(@list), class: "text-reset text-decoration-none" %>
      </div>

    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsWatchList</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %>
  </head>

  <body>
    <%= render 'shared/navbar' %>
    <%= yield %>
  </body>
  <footer>
    <%= render 'shared/footer' %>
  </footer>
</html>

app/views/lists/create.html.erb
<h1>Lists#create</h1>
<p>Find me in app/views/lists/create.html.erb</p>

app/views/lists/index.html.erb
<div class="card-main" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)), url(https://images.unsplash.com/photo-1489599849927-2ee91cede3ba?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=1740&q=80)">
  <p><span data-controller="typed-js"></span></p>
</div>

<div class="container">
  <h4 class="text-center my-4">Choose from the existing lists:</h4>
    <div class="row">
      <div class="col">
        <div class="cards">
        <% @lists.each do |list| %>
            <div class="card-category">
              <%= link_to list.name, list_path(list) %>
            </div>
        <% end %>

        </div>
      </div>
    </div>
</div>

app/views/lists/new.html.erb
<div class="card-category" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)), url(https://images.unsplash.com/photo-1594909122845-11baa439b7bf?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=1740&q=80)">
  <%= @list.name %>
</div>

<div class="container my-4">
  <div class="row">
    <h1>New List</h1>
    <p>Fulfill the information from the form:</p>

      <%= simple_form_for @list do |f| %>
        <%= f.input :name %>
        <%= f.submit class: 'btn btn-flat'%>
      <% end %>
    </div>
  </div>
</div>

app/views/lists/show.html.erb
<div class="card-category" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)), url(https://images.unsplash.com/photo-1585647347384-2593bc35786b?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=1740&q=80)">
  <%= @list.name %>
</div>

<div class="container">
  <div class="row justify-content-around">
    <div class="col-4">
      <h4>(<%= @list.movies.count %>) movies found</h4>
    </div>
    <div class="col-3">
      <%= link_to "Add a movie", new_list_bookmark_path(@list), class: "btn btn-red" %>
    </div>
        <div class="col-3">
      <%= link_to "Delete this list", list_path(@list), class: "btn btn-red", data: { turbo_method: :delete, turbo_confirm: "Are you sure you want to delete the #{@list.name} list?" } %>
    </div>
    <div class="col-12 my-4">
      <% @list.movies.each do |movie|  %>
        <div class="card-product">
          <%= image_tag movie.poster_url, alt: "#{movie.title}"%>
          <div class="card-product-infos">
            <h2><%= movie.title %> - <%= movie.rating%> <i class="fa-sharp fa-solid fa-star"></i></h2>
            <p><%= movie.overview %></p>
            <div class="d-flex justify-content-center">
              <% bookmark = Bookmark.find_by(list: @list, movie: movie) %>
              <%= link_to bookmark_path(bookmark), data: { turbo_method: :delete, turbo_confirm: "Are you sure you want to remove #{movie.title} from your #{@list.name} list"}, class: 'text-danger' do %>
                <i class="fa-solid fa-xmark"></i>
              <% end %>
            </div>
          </div>
        </div>
      <% end %>
    </div>
  </div>
  <hr class="my-5">
  <div class="row">
    <div class="col-12 col-sm-6">
      <h3>(<%= @list.reviews.count%>) reviews</h3>
      <% @list.reviews.each do |review| %>
        <div class="py-2">
          <% review.rating.times do %>
            <i class="fas fa-star star-yellow"></i>
          <% end %>
          <p class="mb-0"><%= review.comment %></p>
          <%= link_to review_path(review), data: { turbo_method: :delete, turbo_confirm: "Are you sure you want to delete this comment from the #{@list.name} list?"}, class: 'text-danger' do %>
            <i class="fa-solid fa-xmark"></i>
          <% end %>
        </div>
      <hr>
      <% end %>
    </div>
    <div class="col-12 col-sm-6">
      <h3>Add a review:</h3>
      <%= simple_form_for [@list, @review] do |f| %>
        <%= f.input :comment %>
        <%= f.input :rating, as: :select, collection: (1..5), required: true, label: "Rate this list", input_html: {data: {controller: "star-rating"}} %>
        <%= f.submit "Validate the review", class:"btn btn-flat" %>
      <% end %>
    </div>
  </div class="my-5">
</div>

app/views/reviews/create.html.erb
<h1>Reviews#create</h1>
<p>Find me in app/views/reviews/create.html.erb</p>

app/views/reviews/destroy.html.erb
<h1>Reviews#destroy</h1>
<p>Find me in app/views/reviews/destroy.html.erb</p>

app/views/shared/_footer.html.erb
<div class="footer">
  <div class="footer-copyright">
    <%= link_to "Homepage", lists_path, class: "text-reset text-decoration-none" %>
  </div>
  <div class="footer-links">
    <a href="#"><i class="fab fa-github"></i></a>
    <a href="#"><i class="fab fa-instagram"></i></a>
    <a href="#"><i class="fab fa-facebook"></i></a>
    <a href="#"><i class="fab fa-twitter"></i></a>
    <a href="#"><i class="fab fa-linkedin"></i></a>
  </div>
</div>

app/views/shared/_navbar.html.erb
    <div class="navbar navbar-expand-sm navbar-light navbar-lewagon">
      <div class="container-fluid">
        <a class="navbar-brand" href="#">
         <img src="https://i.etsystatic.com/8474866/r/il/eddfdc/4818751217/il_570xN.4818751217_rr60.jpg" />
        </a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>

        <div class="collapse navbar-collapse" id="navbarSupportedContent">
          <ul class="navbar-nav me-auto">
            <li class="nav-item active">
              <%= link_to "New list", lists_new_path, class: "btn btn-ghost" %>
            </li>
            <li class="nav-item">
          </ul>
        </div>
      </div>
    </div>